### ISSUE TITLE
Please Release Latest Version

### ISSUE THREAD

**Issue by LilPidgey** [Pyrathlon/Parallax.WPF#1]
Following the Quickstart will not work without the latest code.
I had to download, compile, and add the DLL to my project for it to work. 
Users installing this package from NuGet will not be able to get it to work. ^_^

**Comment by LilPidgey** [comment]
Sorry for the confusion I was installing the wrong version, shouldve went with the github one

**Comment by TheSubGenius** [comment]
Yep, the Nuget was created by @TheKeytrap, but he has not yet updated it to the current source.
For the time being I will push packages here on github. 😃

Please make sure you have a look at the samples since there is no wiki yet.
[ParallaxViews](https://github.com/Pyrathlon/Parallax.WPF/blob/master/Parallax.WPF.Samples/ParallaxViews/ParallaxViews.xaml)
